# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: get nested json property
      id: get_nested_json_property
      uses: 'package.json'
    - run: echo "::set-output name=packageJson::$content"
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://everywhere.vercel.app/api/saveDB'
        method: 'POST'
        data: '{ "from": [1,1], "to": [2,2] }'
